// SPDX-License-Identifier: GPL-3.0-only
// Generated by build_player.py from the audited source build.
namespace HoloPlayer;
internal static class TrustedRuntime { public const string Sha256="58937916bab2f2195f2e8a55f8c3486aca3bf1b6c5621d1ddfe3e5b0ffb3408a"; }
